Repository FRONT-END-BOOTCAMP-PLUS-3/kkultrip, pull requests merged in 2025-02, with the labels that each got.

#2 [style] 헤더 공통컴포넌트 작업
  app/(anon)/spots/[id]/layout.tsx
  app/(anon)/spots/[spotId]/docents/page.tsx
  app/(anon)/spots/[spotId]/images/page.tsx
  app/(anon)/spots/[spotId]/info/page.tsx
  app/(anon)/spots/[spotId]/layout.tsx
  app/(anon)/spots/[spotId]/tips/[tipId]/edit/page.tsx
  app/(anon)/spots/[spotId]/tips/create/page.tsx
  app/(anon)/spots/[spotId]/tips/page.tsx
  app/globals.css
  app/layout.tsx
  components/header/Header.module.scss
  components/header/Header.tsx
  domain/entities/Spot.ts
  domain/entities/Tip.ts
  public/images/logo.svg
Labels: 🎨 style

#3 [setting] admin페이지 레이아웃 분리
  app/(client)/(anon)/login/page.tsx
  app/(client)/(anon)/page.module.css
  app/(client)/(anon)/page.tsx
  app/(client)/(anon)/spots/[spotId]/docents/page.tsx
  app/(client)/(anon)/spots/[spotId]/images/page.tsx
  app/(client)/(anon)/spots/[spotId]/info/page.tsx
  app/(client)/(anon)/spots/[spotId]/layout.tsx
  app/(client)/(anon)/spots/[spotId]/tips/[tipId]/edit/page.tsx
  app/(client)/(anon)/spots/[spotId]/tips/create/page.tsx
  app/(client)/(anon)/spots/[spotId]/tips/page.tsx
  app/(client)/(anon)/spots/page.tsx
  app/(client)/(anon)/users/[kakaoId]/page.tsx
  app/(client)/layout.tsx
  app/(client)/user/page.tsx
  app/layout.tsx
Labels: ⚙ 개발 환경 세팅

#4 [style] spots 페이지 네이버api연결 및 ui 구현
  app/(client)/(anon)/spots/components/BottomSheet.module.scss
  app/(client)/(anon)/spots/components/BottomSheet.tsx
  app/(client)/(anon)/spots/components/DraggableBottomSheet.module.scss
  app/(client)/(anon)/spots/components/DraggableBottomSheet.tsx
  app/(client)/(anon)/spots/components/NaverMap.tsx
  app/(client)/(anon)/spots/components/SearchFilter.module.scss
  app/(client)/(anon)/spots/components/SearchFilter.tsx
  app/(client)/(anon)/spots/page.tsx
  app/layout.tsx
  next.config.ts
  public/images/bee.svg
  public/images/bee_50x58.png
  public/images/flower-activity.svg
  public/images/flower-cafe.svg
  public/images/flower-landmark.svg
  public/images/flower-restaurant.svg
  types/global.d.ts
Labels: ✨ feat, 🎨 style

#5 [feat] 관리자페이지/명소관리
  app/admin/components/Header/Header.module.scss
  app/admin/components/Header/Header.tsx
  app/admin/components/Sidebar/Sidebar.module.scss
  app/admin/components/Sidebar/Sidebar.tsx
  app/admin/components/SpotTable/SpotTable.module.scss
  app/admin/components/SpotTable/SpotTable.tsx
  app/admin/components/TipTable/TipTable.tsx
  app/admin/components/TipTable/Tiptable.module.scss
  app/admin/spots/AdminSpotsPage.module.scss
  app/admin/spots/[id]/edit/SpotsEditPage.module.scss
  app/admin/spots/[id]/edit/page.tsx
  app/admin/spots/create/SpotsCreatePage.module.scss
  app/admin/spots/create/page.tsx
  app/admin/spots/page.tsx
  app/admin/tips/AdminTipsPage.module.scss
  app/admin/tips/page.tsx
  app/admin/users/AdminUsersPage.module.scss
  app/admin/users/page.tsx
  app/api/admin/spots/[id]/route.ts
  app/api/admin/spots/route.ts
  app/api/admin/tips/route.ts
  application/usecases/admin/spot/CreateSpotUseCase.ts
  application/usecases/admin/spot/DeleteSpotUseCase.ts
  application/usecases/admin/spot/GetSpotsByIdUseCase.ts
  application/usecases/admin/spot/GetSpotsUseCase.ts
  application/usecases/admin/spot/UpdateSpotUseCase.ts
  application/usecases/admin/spot/dto/CreateSpotDto.ts
  application/usecases/admin/spot/dto/GetSpotDto.ts
  application/usecases/admin/spot/dto/UpdateSpotDto.ts
  application/usecases/admin/tip/GetTipsUseCase.ts
  application/usecases/admin/tip/dto/GetTipDto.ts
  components/category/Category.module.scss
  components/category/Category.tsx
  components/header/Header.module.scss
  domain/entities/Bookmark.ts
  domain/entities/Docent.ts
  domain/entities/Image.ts
  domain/entities/Reaction.ts
  domain/entities/Spot.ts
  domain/entities/Ticket.ts
  domain/entities/Time.ts
  domain/entities/Tip.ts
  domain/entities/User.ts
  domain/repositories/SpotRepository.ts
  domain/repositories/TipRepository.ts
  infrastructure/repositories/PgSpotRepository.ts
  infrastructure/repositories/PgTipRepository.ts
  lib/prisma.ts
  package-lock.json
  package.json
Labels: ✨ feat, 🎨 style

#6 [file] develop브랜치 병합
  app/(client)/(anon)/spots/page.tsx
  app/api/spots/route.ts
  application/usecases/spot/DfGetSpotsUsecase.ts
  application/usecases/spot/dto/GetSpotsDto.ts
  domain/repositories/BookmarkRepository.ts
  domain/repositories/SpotRepository.ts
  domain/repositories/TimeRepository.ts
  domain/repositories/TipRepository.ts
  infrastructure/repositories/PgBookmarkRepository.ts
  infrastructure/repositories/PgSpotRepository.ts
  infrastructure/repositories/PgTimeRepository.ts
  infrastructure/repositories/PgTipRepository.ts
  package-lock.json
  package.json
Labels: 🐞 fix

#8 [style] user페이지, users페이지 ui구현
  app/(client)/(anon)/users/[kakaoId]/Users.module.scss
  app/(client)/(anon)/users/[kakaoId]/page.tsx
  app/(client)/user/components/Tab.module.scss
  app/(client)/user/components/Tab.tsx
  app/(client)/user/components/TipBox.module.scss
  app/(client)/user/components/TipBox.tsx
  app/(client)/user/layout.tsx
  app/(client)/user/my-tips/page.tsx
  app/(client)/user/page.tsx
  app/(client)/user/spots/page.tsx
  app/(client)/user/spots/spots.module.scss
  app/(client)/user/tips/page.tsx
  app/(client)/user/userLayout.module.scss
  app/globals.css
  components/category/Category.module.scss
  components/category/Category.tsx
  components/spotImageCard/SpotImageCard.module.scss
  components/spotImageCard/SpotImageCard.tsx
  public/images/bee.svg
  public/images/spot.png
  public/images/test.png
Labels: ✨ feat, 🎨 style

#10 [feat] button 컴포넌트 구현
  components/button/Button.module.scss
  components/button/Button.tsx
Labels: ✨ feat, 🎨 style

#11 [feat] 티켓 생성/수정/삭제
  app/admin/components/SpotTable/SpotTable.module.scss
  app/admin/components/SpotTable/SpotTable.tsx
  app/admin/components/TipTable/Tiptable.module.scss
  app/admin/spots/[id]/edit/SpotsEditPage.module.scss
  app/admin/spots/[id]/edit/page.tsx
  app/admin/spots/create/SpotsCreatePage.module.scss
  app/admin/spots/create/page.tsx
  app/admin/spots/page.tsx
  app/admin/tips/page.tsx
  app/api/admin/spots/[id]/[ticketId]/route.ts
  app/api/admin/spots/[id]/route.ts
  app/api/admin/spots/route.ts
  application/usecases/admin/spot/CreateSpotUseCase.ts
  application/usecases/admin/spot/GetSpotsByIdUseCase.ts
  application/usecases/admin/spot/UpdateSpotUseCase.ts
  application/usecases/admin/spot/dto/CreateSpotDto.ts
  application/usecases/admin/spot/dto/GetSpotDto.ts
  application/usecases/admin/spot/dto/UpdateSpotDto.ts
  application/usecases/admin/spot/ticket/dto/CreateTicketDto.ts
  application/usecases/admin/spot/ticket/dto/GetTicketDto.ts
  application/usecases/admin/spot/ticket/dto/UpdateTicketDto.ts
  application/usecases/ticket/DeleteTicketUseCase.ts
  domain/repositories/SpotRepository.ts
  domain/repositories/TicketRepository.ts
  infrastructure/repositories/PgSpotRepository.ts
  infrastructure/repositories/PgTicketRepository.ts
  lib/prisma.ts
  public/images/spots/1740704080186-President_Barack_Obama.jpg
  public/images/spots/President_Barack_Obama 2.jpg
  public/images/spots/President_Barack_Obama 2_1.jpg
  public/images/spots/President_Barack_Obama.jpg
  public/images/spots/President_Barack_Obama_1.jpg
  public/images/spots/President_Barack_Obama_1_2.jpg
  public/images/spots/President_Barack_Obama_1_2_3.jpg
Labels: ✨ feat
