Repository FRONT-END-BOOTCAMP-PLUS-3/kkultrip, pull requests merged in 2025-03, with the labels that each got.

#16 [style] 초기 페이지 추가
  app/(client)/(anon)/IndexPage.module.scss
  app/(client)/(anon)/page.module.css
  app/(client)/(anon)/page.tsx
  components/header/Header.module.scss
  components/header/Header.tsx
Labels: ✨ feat, 🎨 style

#7 [feat] 지도, 명소리스트, 검색, 필터링 기능
  app/(client)/(anon)/spots/Spots.module.scss
  app/(client)/(anon)/spots/components/BottomSheet.module.scss
  app/(client)/(anon)/spots/components/BottomSheet.tsx
  app/(client)/(anon)/spots/components/DraggableBottomSheet.module.scss
  app/(client)/(anon)/spots/components/DraggableBottomSheet.tsx
  app/(client)/(anon)/spots/components/NaverMap.tsx
  app/(client)/(anon)/spots/components/SearchFilter.module.scss
  app/(client)/(anon)/spots/components/SearchFilter.tsx
  app/(client)/(anon)/spots/components/SpotsClient.tsx
  app/(client)/(anon)/spots/page.tsx
  app/api/geocode/route.ts
  app/api/spots/route.ts
  app/globals.css
  application/usecases/spot/GetSpotByNameUsecase.ts
  application/usecases/spot/GetSpotsUsecase.ts
  domain/repositories/SpotRepository.ts
  infrastructure/repositories/PgSpotRepository.ts
  infrastructure/repositories/PgTimeRepository.ts
  public/images/activity.svg
  public/images/bee_50x50.svg
  public/images/bee_50x58.png
  public/images/cafe.svg
  public/images/flower-activity.svg
  public/images/flower-cafe.svg
  public/images/flower-landmark.svg
  public/images/flower-restaurant.svg
  public/images/landmark.svg
  public/images/restaurant.svg
  types/global.d.ts
Labels: ✨ feat

#18 [feat] spots 페이지 동작 방식 변경
  app/(client)/(anon)/page.tsx
  app/(client)/(anon)/spots/components/BottomSheet.module.scss
  app/(client)/(anon)/spots/components/BottomSheet.tsx
  app/(client)/(anon)/spots/components/NaverMap.tsx
  app/(client)/(anon)/spots/components/SearchFilter.module.scss
  app/(client)/(anon)/spots/components/SearchFilter.tsx
  app/(client)/(anon)/spots/components/SpotsClient.tsx
  app/(client)/(anon)/spots/page.tsx
  app/api/spots/route.ts
  application/usecases/spot/dto/GetSpotsDto.ts
  components/header/Header.tsx
  infrastructure/repositories/PgBookmarkRepository.ts
  infrastructure/repositories/PgSpotRepository.ts
  infrastructure/repositories/PgTimeRepository.ts
  infrastructure/repositories/PgTipRepository.ts
  utils/getGeocode.ts
  utils/getMyLocation.ts
Labels: ✨ feat, 🔧 refactor

#20 [feat] repository에 disconnect 추가
  app/(client)/(anon)/spots/components/BottomSheet.tsx
  app/(client)/(anon)/spots/components/SearchFilter.module.scss
  app/api/geocode/route.ts
  infrastructure/repositories/PgBookmarkRepository.ts
  infrastructure/repositories/PgDocentRepository.ts
  infrastructure/repositories/PgImageRepository.ts
  infrastructure/repositories/PgReactionRepository.ts
  infrastructure/repositories/PgReportRepository.ts
  infrastructure/repositories/PgSpotRepository.ts
  infrastructure/repositories/PgTicketRepository.ts
  infrastructure/repositories/PgTimeRepository.ts
  infrastructure/repositories/PgTipRepository.ts
  infrastructure/repositories/PgUserRepository.ts
Labels: ✨ feat, 🐞 fix

#23 [feat] 명소에 에러처리 추가
  app/(client)/(anon)/spots/page.tsx
  infrastructure/repositories/PgBookmarkRepository.ts
Labels: 🔧 refactor

#15 [Feat] 명소 추가, 수정, 삭제
  app/admin/components/header/Header.module.scss
  app/admin/components/header/Header.tsx
  app/admin/components/sidebar/Sidebar.module.scss
  app/admin/components/sidebar/Sidebar.tsx
  app/admin/components/spottable/Spottable.module.scss
  app/admin/components/spottable/Spottable.tsx
  app/admin/components/tiptable/Tiptable.module.scss
  app/admin/components/tiptable/Tiptable.tsx
  app/admin/spots/[id]/edit/SpotsEditPage.module.scss
  app/admin/spots/[id]/edit/page.tsx
  app/admin/spots/create/SpotsCreatePage.module.scss
  app/admin/spots/create/page.tsx
  app/admin/spots/page.tsx
  app/admin/tips/page.tsx
  app/api/admin/spots/[id]/docent/[docentId]/route.ts
  app/api/admin/spots/[id]/route.ts
  app/api/admin/spots/[id]/ticket/[ticketId]/route.ts
  app/api/admin/spots/route.ts
  application/usecases/admin/spot/CreateSpotUseCase.ts
  application/usecases/admin/spot/GetSpotByIdUseCase.ts
  application/usecases/admin/spot/GetSpotListUseCase.ts
  application/usecases/admin/spot/GetSpotsByIdUseCase.ts
  application/usecases/admin/spot/GetSpotsUseCase.ts
  application/usecases/admin/spot/UpdateSpotUseCase.ts
  application/usecases/admin/spot/docent/dto/CreateDocentDto.ts
  application/usecases/admin/spot/docent/dto/DeleteDocentUseCase.ts
  application/usecases/admin/spot/docent/dto/GetDocentDto.ts
  application/usecases/admin/spot/docent/dto/UpdateDocentDto.ts
  application/usecases/admin/spot/dto/CreateSpotDto.ts
  application/usecases/admin/spot/dto/GetSpotDto.ts
  application/usecases/admin/spot/dto/GetSpotListDto.ts
  application/usecases/admin/spot/dto/SpotListDto.ts
  application/usecases/admin/spot/dto/UpdateSpotDto.ts
  application/usecases/admin/spot/ticket/DeleteTicketUseCase.ts
  application/usecases/admin/spot/time/dto/CreateTimeDto.ts
  application/usecases/admin/spot/time/dto/GetTimeDto.ts
  application/usecases/admin/spot/time/dto/UpdateTimeDto.ts
  application/usecases/spot/dto/GetSpotsDto.ts
  domain/repositories/DocentRepository.ts
  domain/repositories/SpotRepository.ts
  domain/repositories/TicketRepository.ts
  domain/repositories/TimeRepository.ts
  infrastructure/repositories/PgDocentRepository.ts
  infrastructure/repositories/PgSpotRepository.ts
  infrastructure/repositories/PgTicketRepository.ts
  infrastructure/repositories/PgTimeRepository.ts
  package.json
  public/images/spots/1740704080186-President_Barack_Obama.jpg
  public/images/spots/President_Barack_Obama 2.jpg
  public/images/spots/President_Barack_Obama 2_1.jpg
  public/images/spots/President_Barack_Obama.jpg
  public/images/spots/President_Barack_Obama_1.jpg
  public/images/spots/President_Barack_Obama_1_2.jpg
  public/images/spots/President_Barack_Obama_1_2_3.jpg
  tsconfig.json
Labels: ✨ feat

#25 [chore] route props 전달 방식 변경
  app/(client)/(anon)/spots/[spotId]/tips/components/TipForm.tsx
  app/(client)/(anon)/spots/[spotId]/tips/components/TipImage.module.scss
  app/api/admin/spots/[id]/route.ts
  app/api/admin/spots/[id]/ticket/[ticketId]/route.ts
  app/api/spots/[spotId]/images/route.ts
  app/api/spots/[spotId]/tips/[tipId]/route.ts
  app/api/tips/[id]/route.ts
  public/images/tips/21_1741327323919_IMG_3400.JPG
Labels: 🔧 refactor

#36 [feat] 전역 상태에 내위치 추가
  app/(client)/(anon)/login/page.tsx
  app/(client)/(anon)/page.tsx
  app/(client)/(anon)/spots/components/BottomSheet.tsx
  app/(client)/(anon)/spots/components/NaverMap.tsx
  app/(client)/(anon)/spots/components/SearchFilter.tsx
  components/header/Header.tsx
  store/useUserStore.ts
Labels: ✨ feat

#38 [style] 로그인 페이지 스타일 변경
  app/(client)/(anon)/login/LoginPage.module.scss
  app/(client)/(anon)/login/page.tsx
  components/button/Button.module.scss
Labels: 🎨 style

#39 [feat] users페이지 꿀팁 조회
  app/(client)/(anon)/users/UsersPage.module.scss
  app/(client)/(anon)/users/[kakaoId]/page.tsx
  app/(client)/(anon)/users/page.tsx
  app/api/users/route.ts
  application/usecases/users/GetUserTipsUsecase.ts
  application/usecases/users/dto/GetUserTipDto.ts
  components/category/Category.module.scss
  components/category/Category.tsx
  domain/repositories/ReactionRepository.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/PgReactionRepository.ts
  infrastructure/repositories/PgUserRepository.ts
Labels: ✨ feat

#40 [feat] 관리자 페이지 꿀팁 이미지 관리
  app/admin/components/searchBar/SearchBar.module.scss
  app/admin/components/searchBar/SearchBar.tsx
  app/admin/images/page.tsx
  app/admin/tips/[tipId]/page.tsx
  app/api/admin/images/route.ts
  app/api/admin/images/spot/[spotName]/route.ts
  app/api/admin/images/user/[userName]/route.ts
  application/usecases/admin/image/GetImageByUserNameUseCase.ts
  application/usecases/admin/image/GetImageListUseCase.ts
  application/usecases/admin/image/dto/GetImageListDto.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/PgUserRepository.ts
Labels: ✨ feat, 🎨 style

#41 [style] 시작페이지 슬로건 추가
  app/(client)/(anon)/IndexPage.module.scss
  app/(client)/(anon)/page.tsx
Labels: 🎨 style

#47 [fix] user페이지, users페이지에서 꿀팁, 이미지 클릭 시 해당 내용으로 이동, 전체적인 UI수정
  README.md
  app/(client)/(anon)/login/page.tsx
  app/(client)/(anon)/signup/SignupPage.module.scss
  app/(client)/(anon)/signup/page.tsx
  app/(client)/(anon)/spots/[spotId]/components/BookMark.tsx
  app/(client)/(anon)/spots/[spotId]/tips/components/CreateTip.tsx
  app/(client)/(anon)/spots/page.tsx
  app/(client)/(anon)/users/UsersPage.module.scss
  app/(client)/(anon)/users/page.tsx
  app/(client)/user/UserLayout.module.scss
  app/(client)/user/bookmarked-spots/BookmarkedSpotsPage.module.scss
  app/(client)/user/bookmarked-spots/page.tsx
  app/(client)/user/components/TipBox.module.scss
  app/(client)/user/components/TipBox.tsx
  app/(client)/user/layout.tsx
  app/(client)/user/my-tips/MyTipsPage.module.scss
  app/(client)/user/my-tips/page.tsx
  app/(client)/user/reacted-tips/ReactedTipsPage.module.scss
  app/(client)/user/reacted-tips/page.tsx
  app/api/spots/route.ts
  app/globals.css
  application/usecases/user/GetBookmarkedSpotsUsecase.ts
  application/usecases/user/dto/GetBookmarkedSpotDto.ts
  components/button/Button.tsx
  components/header/Header.tsx
  components/loading/Loading.module.scss
  components/loading/Loading.tsx
  components/spotImageCard/SpotImageCard.module.scss
  components/spotImageCard/SpotImageCard.tsx
  middleware.ts
  package-lock.json
  package.json
  utils/getGeocode.ts
Labels: ✨ feat, 🎨 style

#48 [feat] dropDown close 기능 추가, 페이지별 헤더 재 설정, 지도로 돌아가는 backHome타입추가
  components/header/Header.module.scss
  components/header/Header.tsx
Labels: ✨ feat

#51 [feat] 유저 정보 수정 기능 구현
  app/(client)/(anon)/users/UsersPage.module.scss
  app/(client)/user/bookmarked-spots/BookmarkedSpotsPage.module.scss
  app/(client)/user/components/UserProfile.module.scss
  app/(client)/user/components/UserProfile.tsx
  app/api/user/route.ts
  application/usecases/user/GetUserUsecase.ts
  application/usecases/user/UpdateUserUsecase.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/PgUserRepository.ts
  store/useUserStore.ts
Labels: ✨ feat

#49 [Fix] 어드민 페이지 QA 반영
  app/admin/components/imageContainer/ImageContainer.module.scss
  app/admin/components/imageContainer/ImageContainer.tsx
  app/admin/components/searchBar/SearchBar.tsx
  app/admin/components/sideBar/SideBar.module.scss
  app/admin/components/sideBar/SideBar.tsx
  app/admin/components/spotTable/SpotTable.module.scss
  app/admin/components/spotTable/SpotTable.tsx
  app/admin/components/tipTable/TipTable.module.scss
  app/admin/components/tipTable/TipTable.tsx
  app/admin/components/userTable/UserTable.module.scss
  app/admin/components/userTable/UserTable.tsx
  app/admin/images/AdminImagesPage.module.scss
  app/admin/images/page.tsx
  app/admin/spots/[id]/edit/SpotsEditPage.module.scss
  app/admin/spots/[id]/edit/page.tsx
  app/admin/spots/create/SpotsCreatePage.module.scss
  app/admin/spots/create/page.tsx
  app/admin/spots/page.tsx
  app/admin/tips/page.tsx
  app/admin/users/page.tsx
  app/api/admin/images/[id]/route.ts
  app/api/admin/images/spot/[spotName]/route.ts
  app/api/admin/images/user/[userName]/route.ts
  app/api/admin/spots/[id]/ticket/[ticketId]/route.ts
  app/api/admin/spots/address/[address]/route.ts
  app/api/admin/spots/route.ts
  app/api/admin/spots/spot/[spotName]/route.ts
  app/api/admin/users/[userId]/route.ts
  app/api/admin/users/route.ts
  application/usecases/admin/image/GetImageByUserNameUseCase.ts
  application/usecases/admin/spot/GetSpotsByAddressUseCase.ts
  application/usecases/admin/spot/GetSpotsByNameUseCase.ts
  application/usecases/admin/tip/GetTipByUserNameUseCase.ts
  application/usecases/admin/user/DeleteUserUseCase.ts
  application/usecases/admin/user/GetUserByNameUseCase.ts
  application/usecases/spot/images/DeleteImageUseCase.ts
  domain/repositories/ImageRepository.ts
  domain/repositories/SpotRepository.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/PgImageRepository.ts
  infrastructure/repositories/PgSpotRepository.ts
  infrastructure/repositories/PgUserRepository.ts
Labels: 🐞 fix

#75 [feat] 지도 이동 후 해당위치 기준 검색기능 추가
  app/(client)/(anon)/spots/components/NaverMap.module.scss
  app/(client)/(anon)/spots/components/NaverMap.tsx
  types/global.d.ts
Labels: ✨ feat, 🎨 style

#77 [style] z인덱스 조정, hidden SEO 삭제
  app/(client)/(anon)/spots/SpotsPage.module.scss
  app/(client)/(anon)/spots/components/BottomSheet.module.scss
  app/(client)/(anon)/spots/page.tsx
Labels: 🎨 style

#78 [style] root container 높이 100vh->100dvh로 변경
  app/(client)/(anon)/spots/components/NaverMap.module.scss
  app/globals.css
Labels: 🎨 style, 🔧 refactor
